config/routes.rb
Rails.application.routes.draw do
  get '/', controller: 'index', action: 'index'

  resources :feeds do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
=begin
According to the RSS specification https://validator.w3.org/feed/docs/rss2.html

Mandatory Fields
- url
- title
- description

Optional Fields
- language
- published_at
TODO
- lastBuildDate
- generator
- image
- ttl (integer in minutes)
- copyright
- managingEditor
- webMaster
=end

class Feed < ApplicationRecord
  validates :url, uniqueness: true, presence: true
  validates :title, presence: true
  has_many :items, dependent: :destroy
end

app/models/item.rb
=begin
title
link
description
pubDate
guid
category
comments

dc_creator
content_encoded
=end
class Item < ApplicationRecord
  belongs_to :feed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to @feed, notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /feeds/1
  def update
    if @feed.update(feed_params)
      redirect_to @feed, notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /feeds/1
  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:url, :title, :description, :language, :published_at)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @items = Item.order(published_at: :desc).limit(25)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_feed

  # GET /items
  def index
    @items = Item.where(feed: @feed)
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to feed_item_path(@feed, @item), notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to feed_item_path(@feed, @item), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to feed_items_url(@feed), notice: 'Item was successfully destroyed.'
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def set_feed
    @feed = Feed.find(params[:feed_id])
  end

  def item_params
    params.require(:item).permit(:url, :title, :description, :published_at, :guid, :feed_id, :category, :comments)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :feed_url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :feed_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :feed_description %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language, id: :feed_language %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, id: :feed_published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>
      <th>Language</th>
      <th>Published at</th>
      <th>Feed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.url %></td>
        <td><%= feed.title %></td>
        <td><%= feed.description %></td>
        <td><%= feed.language %></td>
        <td><%= feed.published_at %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<p>
  <strong>Language:</strong>
  <%= @feed.language %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @feed.published_at %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/index/index.html.erb
<table id="gr-body">
  <tbody>
    <% @items.each_with_index do |item, i| %>
    <tr class="item <% if i%2 == 1 %>odd<% end %>">
      <td class="item-number"><%= i %>.</td>
      <td>
        <span class="item-title"><%= link_to item.title.html_safe, item.url %></span><br />
        <small class="item-details">
          <%= item.feed.title %>
          | <%= time_ago_in_words(item.published_at) %> ago
          <% if item.category %> | <%= item.category %><% end %>
          <% if item.comments %> | <%= link_to "comments", item.comments %><% end %>
        </small>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true, url: url) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :item_url %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :item_description %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, id: :item_published_at %>
  </div>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid, id: :item_guid %>
  </div>

  <div class="field">
    <%= form.label :feed_id %>
    <%= form.hidden_field :feed_id, value: @feed.id %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_field :comments, id: :item_comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item, feed: @feed, url: feed_item_path(@feed, @item) %>

<%= link_to 'Show', feed_item_path(@feed, @item) %> |
<%= link_to 'Back', feed_items_path(@feed) %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>
      <th>Published at</th>
      <th>Guid</th>
      <th>Feed</th>
      <th>Category</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.url %></td>
        <td><%= item.title %></td>
        <td><%= item.description.html_safe %></td>
        <td><%= item.published_at %></td>
        <td><%= item.guid %></td>
        <td><%= link_to item.feed.title, item.feed %></td>
        <td><%= item.category %></td>
        <td><%= item.comments %></td>
        <td><%= link_to 'Show', feed_item_url(item.feed, item) %></td>
        <td><%= link_to 'Edit', edit_feed_item_path(item.feed, item) %></td>
        <td><%= link_to 'Destroy', feed_item_url(item.feed,item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_feed_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item, feed: @feed, url: feed_items_path(@feed) %>

<%= link_to 'Back', feed_items_path(@feed) %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @item.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description.html_safe %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @item.published_at %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @item.guid %>
</p>

<p>
  <strong>Feed:</strong>
  <%= link_to @item.feed.title, feed_url(@item.feed) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @item.comments %>
</p>

<%= link_to 'Edit', edit_feed_item_path(@item.feed, @item) %> |
<%= link_to 'Back', feed_items_path(@item.feed) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greader</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <table id="gr-main">
      <tr>
        <table id="gr-header">
          <tr>
            <th>GReader</th>
          </tr>
        </table>
      </tr>

      <tr>
        <%= yield %>
      </tr>
    </table>
  </body>
</html>